// UCM Actions
export const GET_UCMS = 'GET_UCMS'
export const ADD_UCM = 'ADD_UCM'
export const UPDATE_UCM = 'UPDATE_UCM'
export const DELETE_UCM = 'DELETE_UCM'

// Query Actions
export const QUERY_INITIATED = 'QUERY_INITIATED'
export const QUERY_COMPLETED = 'QUERY_COMPLETED'
export const UPDATE_QUERY = 'UPDATE_QUERY'
export const RECIEVED_RESULTS = 'RECIEVED_RESULTS'
export const CLEAR_RESULTS = 'CLEAR_RESULTS'
export const UPDATE_TARGETS = 'UPDATE_TARGETS'
export const REMOVE_TARGET = 'REMOVE_TARGET'
export const EXPORT_INITIATED = 'EXPORT_INITIATED'
export const EXPORT_COMPLETED = 'EXPORT_COMPLETED'

// Favorites Actions
export const GET_FAVORITES = 'GET_FAVORITES'
export const UPDATE_FAVORITE = 'UPDATE_FAVORITE'
export const FAVORITE_QUERY = 'FAVORITE_QUERY'
export const UNFAVORITE_QUERY = 'UNFAVORITE_QUERY'

// Updater Actions
export const UPDATE_AVAILABLE = 'UPDATE_AVAILABLE'
export const UPDATE_DOWNLOADING = 'UPDATE_DOWNLOADING'
export const UPDATE_READY = 'UPDATE_READY'
export const UPDATE_FAILED = 'UPDATE_FAILED'
